# This is a basic workflow to help you get started with Actions

name: Gif Comment Action

# Controls when the action will run. 
on:
  # Triggers the workflow on open issues
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  comment:
    if: github.event_name == 'issues'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Add a GIF comment
        id: GifComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: $${{ secrets.GIPHY_KEY }}
          comment_type: 'gif'
